### ISSUE TITLE
Feature Request: adb shell

### ISSUE THREAD

**Issue by ahmedre** [nassendelft/alfred-android-adb#1]
Thanks for writing this, I stumbled across it today and can imagine this will save a lot of time, so thank you.

I had a request - it'd be awesome to have an "adb shell" command via Alfred that passed the proper device id and opened it in a new terminal (ideally with us being able to configure whether to use the stock Terminal.app or iterm2). Moreover, would be awesome to be able to specify an optional default directory to land in by default (ex /sdcard)

**Comment by nassendelft** [comment]
Hi, sorry for the (very) late reply. I do still update once in a while. And I did look into this. But unfortunately I couldn't get it quite to work. I've tried several approaches but the build in terminal isn't really build for starting and running commands.

I'm open to any suggestions though. Closing this for now unless someone comes up with a better idea
